config/routes.rb
Rails.application.routes.draw do
  resources :sketches
 root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sketch.rb
class Sketch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def  index
	end

end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController
  before_action :set_sketch, only: [:show, :edit, :update, :destroy]

  # GET /sketches
  # GET /sketches.json
  def index
    @sketches = Sketch.all
  end

  # GET /sketches/1
  # GET /sketches/1.json
  def show
  end

  # GET /sketches/new
  def new
    @sketch = Sketch.new
  end

  # GET /sketches/1/edit
  def edit
  end

  # POST /sketches
  # POST /sketches.json
  def create
    @sketch = Sketch.new(sketch_params)

    respond_to do |format|
      if @sketch.save
        format.html { redirect_to @sketch, notice: 'Sketch was successfully created.' }
        format.json { render :show, status: :created, location: @sketch }
      else
        format.html { render :new }
        format.json { render json: @sketch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sketches/1
  # PATCH/PUT /sketches/1.json
  def update
    respond_to do |format|
      if @sketch.update(sketch_params)
        format.html { redirect_to @sketch, notice: 'Sketch was successfully updated.' }
        format.json { render :show, status: :ok, location: @sketch }
      else
        format.html { render :edit }
        format.json { render json: @sketch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sketches/1
  # DELETE /sketches/1.json
  def destroy
    @sketch.destroy
    respond_to do |format|
      format.html { redirect_to sketches_url, notice: 'Sketch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sketch
      @sketch = Sketch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sketch_params
      params.require(:sketch).permit(:image, :kind, :date, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sketches_helper.rb
module SketchesHelper
end

app/views/home/index.html.erb
<center> 
	<h1> Bienvenue </h1>

	<img src="https://i.pinimg.com/originals/9b/b2/b5/9bb2b57f4ee54c28e781ef2753ddea24.jpg"
	 alt ="Coco Chanel et Lagarfeld"
	 height ="573.5"
	 width ="400px"
	 >

</center>


	 

app/views/layouts/_navigation.html.erb
<header>
	<button <div><img src="https://i.pinimg.com/originals/fe/28/79/fe2879c7ed656b16a3d8b8c346f91a74.png" class="favorite styled"
		height ="50 px"
		width ="50px"
        type="button"></div>
	<%=link_to 'Mon Musée', root_path %>
	</button>

	<nav>
		<button class="favorite styled"
        type="button">
		<%= link_to 'Entrer dans le musée', sketches_path %>
		</button>

	</nav>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FashionSketch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/sketches/_form.html.erb
<%= form_with(model: sketch, local: true) do |form| %>
  <% if sketch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sketch.errors.count, "error") %> prohibited this sketch from being saved:</h2>

      <ul>
      <% sketch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= form.text_field :kind %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sketches/edit.html.erb
<h1>Editing Sketch</h1>

<%= render 'form', sketch: @sketch %>

<%= link_to 'Show', @sketch %> |
<%= link_to 'Back', sketches_path %>

app/views/sketches/index.html.erb
<p id="notice"><%= notice %></p>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<h1>Sketches</h1>
<table>
  <table class="table">

  <thead>
    <tr>
      <th>Image</th>
      <th>kind</th>
      <th>Date</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sketches.each do |sketch| %>
      <tr>
       
        <td><%= image_tag sketch.image, class: 'img-fluid'%></td>
        <td><%= sketch.kind %></td>
        <td><%= sketch.date %></td>
        <td><%= sketch.name %></td>
        <td><%= link_to 'Show', sketch %></td>
        <td><%= link_to 'Edit', edit_sketch_path(sketch) %></td>
        <td><%= link_to 'Destroy', sketch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sketch', new_sketch_path %>

app/views/sketches/new.html.erb
<h1>New Sketch</h1>

<%= render 'form', sketch: @sketch %>

<%= link_to 'Back', sketches_path %>

app/views/sketches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @sketch.image %>
</p>

<p>
  <strong>kind:</strong>
  <%= @sketch.kind %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sketch.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sketch.name %>
</p>

<%= link_to 'Edit', edit_sketch_path(@sketch) %> |
<%= link_to 'Back', sketches_path %>